## 1. 데이터 불러오기

In [31]:
import pandas as pd

titan = pd.read_csv('../data/06_(문제)타이타닉_분류_데이터셋.csv')
titan

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

### 1-1. 데이터 확인

In [32]:
titan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [10]:
titan.corr()

survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500   
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067   
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.280328  0.198270  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

## 2. embarked 결측값 분류하기

### 2-1. 데이터 정제
- 필요 없는 컬럼 제거

In [33]:
titan = titan.drop(columns=['deck', 'class','alive', 'embark_town'])

- 컬럼 타입 변경

In [34]:
titan[['adult_male','alone']] = titan[['adult_male','alone']].astype('int')

- 예측할 데이터 생성

In [35]:
data1 = titan[(titan['embarked'].isnull() == False) & (titan['age'].isnull() == False)]
pred1 = titan[titan['embarked'].isnull() == True]

- 타겟 데이터 생성

In [36]:
target = data1['embarked']

In [37]:
target = target.replace({'C':0,
                         'Q':1,
                         'S':2})

- 원핫인코딩

In [38]:
data1 = data1.drop(columns=['embarked'])

In [39]:
data1 = pd.get_dummies(data1)
pred1 = pd.get_dummies(pred1)

In [40]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    712 non-null    int64  
 1   pclass      712 non-null    int64  
 2   age         712 non-null    float64
 3   sibsp       712 non-null    int64  
 4   parch       712 non-null    int64  
 5   fare        712 non-null    float64
 6   adult_male  712 non-null    int32  
 7   alone       712 non-null    int32  
 8   sex_female  712 non-null    uint8  
 9   sex_male    712 non-null    uint8  
 10  who_child   712 non-null    uint8  
 11  who_man     712 non-null    uint8  
 12  who_woman   712 non-null    uint8  
dtypes: float64(2), int32(2), int64(4), uint8(5)
memory usage: 48.0 KB


In [41]:
pred1[['sex_male', 'who_child','who_man']] = 0

In [42]:
pred1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 61 to 829
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    2 non-null      int64  
 1   pclass      2 non-null      int64  
 2   age         2 non-null      float64
 3   sibsp       2 non-null      int64  
 4   parch       2 non-null      int64  
 5   fare        2 non-null      float64
 6   adult_male  2 non-null      int32  
 7   alone       2 non-null      int32  
 8   sex_female  2 non-null      uint8  
 9   who_woman   2 non-null      uint8  
 10  sex_male    2 non-null      int64  
 11  who_child   2 non-null      int64  
 12  who_man     2 non-null      int64  
dtypes: float64(2), int32(2), int64(7), uint8(2)
memory usage: 180.0 bytes


- 생성된 변수들 배열화

In [43]:
data1 = data1.to_numpy()
target = target.to_numpy()
pred1 = pred1.to_numpy()

### 2-2. 데이터 분리

In [44]:
# 데이터분리
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(
    data1, target, random_state=111, stratify = target)

print(train_data.shape, train_target.shape)
print(test_data.shape, test_target.shape)

(534, 13) (534,)
(178, 13) (178,)


### 2-3. 랜덤포레스트

In [45]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, random_state=111)
rf.fit(train_data, train_target)

print(rf.score(train_data, train_target))
print(rf.score(test_data, test_target))

0.9962546816479401
0.797752808988764


In [46]:
# 교차검증
from sklearn.model_selection import cross_validate
import numpy as np

rf = RandomForestClassifier(n_jobs=-1, random_state=111)
scores = cross_validate(rf, train_data, train_target,
                        return_train_score=True, n_jobs=-1)

print(scores)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

rf.fit(train_data, train_target)

print(rf.feature_importances_)

{'fit_time': array([0.172539  , 0.17337966, 0.14960051, 0.20049477, 0.20048189]), 'score_time': array([0.01994777, 0.01993608, 0.02094483, 0.02292657, 0.02194142]), 'test_score': array([0.79439252, 0.8411215 , 0.70093458, 0.77570093, 0.78301887]), 'train_score': array([0.99765808, 0.99765808, 0.99765808, 0.99765808, 0.9953271 ])}
0.9971918842609819 0.7790336801269617
[0.02897679 0.07235062 0.29522306 0.05711179 0.05101514 0.42057389
 0.00846869 0.02115112 0.00644854 0.00866368 0.01215326 0.0073813
 0.01048211]


In [47]:
print(rf.predict(test_data[:5]))
print(test_target[:5])

[2 2 0 2 2]
[2 2 2 2 2]


### 2-4. 엑스트라 트리

In [48]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs=-1, random_state=111)
et.fit(train_data, train_target)

print(et.score(train_data, train_target))
print(et.score(test_data, test_target))

0.9962546816479401
0.7808988764044944


In [49]:
print(et.predict(test_data[:5]))
print(test_target[:5])

[2 2 0 2 2]
[2 2 2 2 2]


### 2-5. 그레디언트 부스팅

In [50]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=111)
gb.fit(train_data, train_target)

print(gb.score(train_data, train_target))
print(gb.score(test_data, test_target))

0.9662921348314607
0.8202247191011236


In [51]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=111)
scores = cross_validate(gb, train_data, train_target,
                        return_train_score=True, n_jobs=-1)

print(scores)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

gb.fit(train_data, train_target)

print(et.feature_importances_)

{'fit_time': array([0.36869192, 0.35233283, 0.34222126, 0.32988262, 0.37726831]), 'score_time': array([0.00059509, 0.00099707, 0.0009973 , 0.00099635, 0.0009973 ]), 'test_score': array([0.8411215 , 0.8411215 , 0.80373832, 0.77570093, 0.83018868]), 'train_score': array([0.97423888, 0.9765808 , 0.96252927, 0.96955504, 0.97663551])}
0.9719078990566656 0.8183741844471875
[0.03052815 0.08491248 0.3002064  0.05814283 0.05974653 0.40070727
 0.00603424 0.01884103 0.00774774 0.00617085 0.01361782 0.00403628
 0.0093084 ]


In [53]:
print(et.predict(test_data[:5]))
print(test_target[:5])

[2 2 0 2 2]
[2 2 2 2 2]


### alone, pclass 독립변수

In [54]:
data1 = titan[(titan['embarked'].isnull() == False) & (titan['age'].isnull() == False)]
data2 = data1[['alone', 'pclass']]
data2.to_numpy()

array([[0, 3],
       [0, 1],
       [1, 3],
       ...,
       [1, 1],
       [1, 1],
       [1, 3]], dtype=int64)

In [55]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(
    data2, target, random_state=111, stratify = target)

print(train_data.shape, train_target.shape)
print(test_data.shape, test_target.shape)

(534, 2) (534,)
(178, 2) (178,)


In [56]:
# 교차검증

from sklearn.model_selection import cross_validate
import numpy as np

rf = RandomForestClassifier(n_jobs=-1, random_state=111)
scores = cross_validate(rf, train_data, train_target,
                        return_train_score=True, n_jobs=-1)

print(scores)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

rf.fit(train_data, train_target)

print(rf.feature_importances_)

{'fit_time': array([0.15396047, 0.15173125, 0.14116645, 0.19073176, 0.19372439]), 'score_time': array([0.02094436, 0.02194166, 0.01994681, 0.02494287, 0.02493334]), 'test_score': array([0.78504673, 0.77570093, 0.77570093, 0.77570093, 0.78301887]), 'train_score': array([0.77751756, 0.77985948, 0.77985948, 0.77985948, 0.77803738])}
0.7790266803825865 0.7790336801269617
[0.10725995 0.89274005]


In [57]:
print(rf.predict(test_data[:10]))
print(test_target[:10])

[2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 0 2 2 2 1]


In [58]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=111)
scores = cross_validate(gb, train_data, train_target,
                        return_train_score=True, n_jobs=-1)

print(scores)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

gb.fit(train_data, train_target)

print(gb.feature_importances_)

{'fit_time': array([0.27581048, 0.23389959, 0.2527678 , 0.26629186, 0.27441096]), 'score_time': array([0.0029943 , 0.00300765, 0.00207853, 0.00099754, 0.00299191]), 'test_score': array([0.78504673, 0.77570093, 0.77570093, 0.77570093, 0.78301887]), 'train_score': array([0.77751756, 0.77985948, 0.77985948, 0.77985948, 0.77803738])}
0.7790266803825865 0.7790336801269617
[0.09072827 0.90927173]


In [59]:
print(gb.predict(test_data[:10]))
print(test_target[:10])

[2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 0 2 2 2 1]


In [60]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import cross_validate

hgb = HistGradientBoostingClassifier(random_state=111)
scores = cross_validate(hgb, train_data, train_target,
                        return_train_score=True, n_jobs=-1)

print(scores)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

hgb.fit(train_data, train_target)
hgb.score(test_data, test_target)

{'fit_time': array([0.23239636, 0.22840762, 0.17948174, 0.23838115, 0.22242546]), 'score_time': array([0.00797844, 0.00797868, 0.00498629, 0.00804925, 0.00897503]), 'test_score': array([0.78504673, 0.77570093, 0.77570093, 0.77570093, 0.78301887]), 'train_score': array([0.77751756, 0.77985948, 0.77985948, 0.77985948, 0.77803738])}
0.7790266803825865 0.7790336801269617


0.7752808988764045

In [26]:
print(hgb.predict(test_data[:10]))
print(test_target[:10])

[2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 0 2 2 2 1]
