In [53]:
# 필요한 모듈 호출
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

# 텐서플로우 모듈
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.utils import plot_model, to_categorical
from tensorflow.keras.losses import binary_crossentropy, CategoricalCrossentropy
from keras.datasets import mnist

In [145]:
# 데이터 수집
(x_train_full, y_train_full),(x_test, y_test) = mnist.load_data()

In [146]:
print(x_train_full.shape)
print(y_train_full.shape)

(60000, 28, 28)
(60000,)


In [147]:
x_train, x_val, y_train, y_val = \
    train_test_split(x_train_full, y_train_full)

In [148]:
x1 = x_train.shape[1]
x2 = x_train.shape[2]
x_train = x_train.reshape(-1, x1*x2)
x_val = x_val.reshape(-1, x1*x2)
x_test = x_test.reshape(-1, x1*x2)

In [149]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_val = to_categorical(y_val)

In [150]:
input_shape = x_train.shape[1:]
output_shape = y_train.shape[1]

In [68]:
print(input_shape)
print(output_shape)

(784,)
10


In [69]:
model1 = Sequential()
model1.add(Dense(1024, activation ='relu', input_shape=input_shape))
model1.add(Dense(512, activation ='relu'))
model1.add(Dense(output_shape, activation ='softmax'))

In [70]:
model2 = Sequential(
        [
            Dense(1024, activation='relu', input_shape=input_shape),
            Dense(512, activation ='relu'),
            Dense(output_shape, activation ='softmax'),
        ]
)

In [71]:
input_ = Input(shape = input_shape)
l1 = Dense(1024, activation='relu')(input_)
l2 = Dense(512, activation ='relu')(l1)
output_ = Dense(output_shape, activation ='softmax')(l2)

model3 = Model(inputs=[input_], outputs=[output_])

In [72]:
optimizer = RMSprop()
loss = CategoricalCrossentropy()
metrics = ['accuracy']

In [73]:
model1.compile(optimizer= optimizer,
               loss = loss,
               metrics= metrics
               )

model2.compile(optimizer= optimizer,
               loss = loss,
               metrics= metrics
               )

model3.compile(optimizer= optimizer,
               loss = loss,
               metrics= metrics
               )

In [74]:
model1.fit(x_train,
           y_train,
           epochs=10,
           batch_size = 400,
           validation_data=(x_val, y_val))

model2.fit(x_train,
           y_train,
           epochs=10,
           batch_size = 400,
           validation_data=(x_val, y_val))

model3.fit(x_train,
           y_train,
           epochs=10,
           batch_size = 400,
           validation_data=(x_val, y_val))

model1_result = model1.evaluate(x_test, y_test)
model2_result = model1.evaluate(x_test, y_test)
model3_result = model1.evaluate(x_test, y_test)

Epoch 1/10
113/113 [==============================] - 3s 22ms/step - loss: 17.1520 - accuracy: 0.8364 - val_loss: 0.5750 - val_accuracy: 0.9404
Epoch 2/10
113/113 [==============================] - 2s 20ms/step - loss: 0.5385 - accuracy: 0.9351 - val_loss: 0.9314 - val_accuracy: 0.8738
Epoch 3/10
113/113 [==============================] - 2s 22ms/step - loss: 0.2910 - accuracy: 0.9547 - val_loss: 0.4972 - val_accuracy: 0.9384
Epoch 4/10
113/113 [==============================] - 2s 20ms/step - loss: 0.2236 - accuracy: 0.9640 - val_loss: 0.2871 - val_accuracy: 0.9617
Epoch 5/10
113/113 [==============================] - 3s 24ms/step - loss: 0.1843 - accuracy: 0.9702 - val_loss: 0.3908 - val_accuracy: 0.9494
Epoch 6/10
113/113 [==============================] - 2s 20ms/step - loss: 0.1594 - accuracy: 0.9741 - val_loss: 0.4061 - val_accuracy: 0.9559
Epoch 7/10
113/113 [==============================] - 2s 21ms/step - loss: 0.1468 - accuracy: 0.9767 - val_loss: 0.4320 - val_accuracy: 0.960

In [76]:
print(model1_result)
print(model2_result)
print(model3_result)

[0.4420497417449951, 0.9666000008583069]
[0.4420497417449951, 0.9666000008583069]
[0.4420497417449951, 0.9666000008583069]


In [103]:
model4 = Sequential()
l1 = Dense(1024, input_shape= input_shape, activation = 'sigmoid')
l2 = Dense(512, activation ='sigmoid')
out = Dense(output_shape, activation = 'softmax')

model4.add(l1)
model4.add(l2)
model4.add(out)

model5 = Sequential(
        [
         l1,
         l2,
         out
        ]
)
input_ = Input(shape =input_shape)
layer1 = l1(input_)
layer2 = l2(layer1)
output_ = out(layer2)

model6 = Model(inputs = [input_], outputs =[output_])

In [104]:
model4.layers[0].get_weights()[0]

array([[ 0.02658674, -0.02672465, -0.04435593, ...,  0.0164571 ,
        -0.0175196 ,  0.01056575],
       [-0.0427243 , -0.02091216, -0.01348579, ...,  0.03913102,
         0.03208362,  0.01492956],
       [-0.04202013, -0.00843723, -0.02447345, ...,  0.05497674,
        -0.04443869, -0.00713075],
       ...,
       [-0.05584696, -0.0473906 , -0.04268008, ..., -0.01206711,
        -0.05581775, -0.02058504],
       [ 0.04652879,  0.04543196, -0.03309656, ...,  0.0352075 ,
        -0.02438034,  0.05201242],
       [ 0.00664478, -0.01905608, -0.02003508, ...,  0.00044754,
        -0.00844408, -0.01426196]], dtype=float32)

In [105]:
model5.layers[0].set_weights([model4.layers[0].get_weights()[0],
                              model4.layers[0].get_weights()[1]])

In [106]:
model5.layers[1].get_weights()[0]

array([[ 0.05209352, -0.01652952, -0.0173744 , ...,  0.04705472,
         0.00863801, -0.00060713],
       [-0.03291358,  0.04568323, -0.03057523, ..., -0.02011156,
        -0.03947467,  0.05153629],
       [-0.04694629,  0.00371315,  0.00516039, ..., -0.0123347 ,
         0.00162414, -0.03181472],
       ...,
       [ 0.01553053, -0.0205688 ,  0.05695686, ..., -0.0018692 ,
         0.00100921, -0.00901085],
       [-0.03401139, -0.00450732, -0.00548504, ...,  0.04689234,
        -0.05889447,  0.01606618],
       [ 0.02175233, -0.06127331, -0.01310666, ..., -0.02951972,
        -0.01079042, -0.01967299]], dtype=float32)

In [107]:
for i in range(len(model4.layers)):
    model5.layers[i].set_weights([model4.layers[i].get_weights()[0],
                                 model4.layers[i].get_weights()[1]])
    model6.layers[i+1].set_weights([model4.layers[i].get_weights()[0],
                                 model4.layers[i].get_weights()[1]])

In [108]:
np.sum(model5.layers[2].get_weights()[0])

-5.0120196

In [109]:
np.sum(model4.layers[2].get_weights()[0])

-5.0120196

In [112]:
optimizer = 'rmsprop'
loss = "categorical_crossentropy"
model4.compile(optimizer= optimizer,
               loss= loss)
model5.compile(optimizer= optimizer,
               loss= loss)
model6.compile(optimizer= optimizer,
               loss= loss)

In [115]:
model4.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
model5.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
model6.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
print(model4.evaluate(x_test, y_test))
print(model5.evaluate(x_test, y_test))
print(model6.evaluate(x_test, y_test))

313/313 [==============================] - 1s 3ms/step - loss: 0.1092
0.1092308983206749
313/313 [==============================] - 1s 3ms/step - loss: 0.1092
0.1092308983206749
313/313 [==============================] - 1s 3ms/step - loss: 0.1092
0.1092308983206749


In [118]:
print(np.sum(np.argmax(model4.predict(x_test),axis=1) == np.argmax(y_test,axis=1) / len(y_test)))
print(np.sum(np.argmax(model5.predict(x_test),axis=1) == np.argmax(y_test,axis=1) / len(y_test)))
print(np.sum(np.argmax(model6.predict(x_test),axis=1) == np.argmax(y_test,axis=1) / len(y_test)))

938
938
938


In [121]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [122]:
def softmax(x):
    c = np.max(x,axis=1).reshape(-1,1)
    x = x-c
    return np.exp(x)/np.sum(np.exp(x),axis=1).reshape(-1,1)

In [123]:
import numpy as np
class Relu:
    def __init__(self):
        self.mask = None
    def forward(self,x):
        self.mask = (x <=0)
        out = x.copy()
        out[self.mask] = 0
        return out
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout
        return dx
        
class Sigmoid:
    def __init__(self):
        self.out = None
    
    def forward(self,x):
        out = sigmoid(x)
        self.out = out
        return out
    
    def backward(self,dout):
        dx = ((1-self.out)*self.out)*dout
        return dx

class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.origin_shape = None
        self.dW = None
        self.db = None
    
    def forward(self,x):
        self.origin_shape = x.shape
        self.x = x
        out = np.dot(x,self.W) + self.b
        return out
    
    def backward(self,dout):
        dx = np.dot(dout,self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)
        dx = dx.reshape(self.origin_shape)
        return dx

class Loss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    
    def forward(self,t,y):
        self.y = softmax(y)
        self.t = t
        self.loss = categorical_crossentropy(self.t, self.y)
        return self.loss
    
    def backward(self,dout=1):
        dx = (self.y - self.t)*dout
        return dx

In [120]:
l_1_w = model4.layers[0].get_weights()[0]
l_1_b = model4.layers[0].get_weights()[1]
# sigmoid
l_2_w = model4.layers[1].get_weights()[0]
l_2_b = model4.layers[1].get_weights()[1]
# sigmoid
l_3_w = model4.layers[2].get_weights()[0]
l_3_b = model4.layers[2].get_weights()[1]

In [124]:
a = np.dot(x_test, l_1_w) + l_1_b
a = sigmoid(a)
a = np.dot(a, l_2_w) + l_2_b
a = sigmoid(a)
a = np.dot(a, l_3_w) + l_3_b

C:\Users\admin\AppData\Local\Temp\ipykernel_11908\4033946986.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [129]:
np.sum(np.argmax(a, axis=1) == np.argmax(y_test,axis=1)) / len(y_test)

0.9744

In [132]:
# 모델 저장 모듈
from keras.models import save_model
from keras.models import load_model

In [139]:
# 모델 저장
save_model(model4,'./models/model4.h6')
save_model(model5,'./models/model5.h5')
save_model(model6,'./models/model6.h4')

INFO:tensorflow:Assets written to: ./models/model4.h6\assets
INFO:tensorflow:Assets written to: ./models/model6.h4\assets


In [140]:
model4_1 = load_model('./models/model4.h6')
model5_1 = load_model('./models/model5.h5')
model6_1 = load_model('./models/model6.h4')

In [160]:
model7 = Sequential([
    Dense(1024,input_shape =input_shape, activation ='relu'),
    Dense(512, activation ='relu'),
    Dense(output_shape, activation ='softmax')
    ])

model8 = Sequential([
    Dense(1024,input_shape =input_shape, activation ='relu'),
    Dense(512, activation ='relu'),
    Dense(output_shape, activation ='softmax')
    ])

model9 = Sequential([
    Dense(1024,input_shape =input_shape, activation ='relu'),
    Dense(512, activation ='relu'),
    Dense(output_shape, activation ='softmax')
    ])

In [154]:
np.zeros_like(model7.layers[0].get_weights()[0])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [162]:
model7.layers[0].set_weights([np.ones_like(model1.layers[0].get_weights()[0]),
                                np.zeros_like(model1.layers[0].get_weights()[1])])

In [163]:
model8.layers[1].set_weights([np.ones_like(model1.layers[1].get_weights()[0]),
                                np.zeros_like(model1.layers[1].get_weights()[1])])

In [167]:
optimizer = 'rmsprop'
loss = "categorical_crossentropy"
metrics = ['accuracy']
model7.compile(optimizer= optimizer,
               loss= loss,
               metrics= metrics)
model8.compile(optimizer= optimizer,
               loss= loss,
               metrics= metrics)
model9.compile(optimizer= optimizer,
               loss= loss,
               metrics= metrics)

In [166]:
model7.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
model8.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
model9.fit(x_train, y_train, epochs=10, batch_size = 100, verbose =0)
print(model7.evaluate(x_test, y_test))
print(model8.evaluate(x_test, y_test))
print(model9.evaluate(x_test, y_test))

313/313 [==============================] - 1s 2ms/step - loss: 2.3009
2.3008952140808105
313/313 [==============================] - 1s 2ms/step - loss: 2.5177
2.5177438259124756
313/313 [==============================] - 1s 2ms/step - loss: 0.4663
0.46629461646080017
