In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
from matplotlib import font_manager, rc
import platform

# seaborn 설정 리셋
sns.reset_defaults()

# 폰트설정
if platform.system() == 'Windows' :
    path = 'c:/Windows/Fonts/malgun.ttf'
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
elif platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
else :
    print('Check your OS System')
    
# 그래프에 마이너스 표시
matplotlib.rcParams['axes.unicode_minus'] = False

In [3]:
# 1. NAND w1, w2, theta
# 2. AND w1, w2, theta
# 3. OR w1, w2, theta
# 함수 and논리를 출력하는 함수
# 함수 nand논리를 출력하는 함수
# 함수 or논리를 출력하는 함수
# 함수 xor논리를 출력하는 함수

In [4]:
X = np.array([[0,0,1,1],[0,1,0,1]]).T

In [5]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [298]:
def AND(x) :
    W =np.array([[0.1], [0.1]]) 
    theta = 0.1
    return np.where(np.dot(x, W) > theta, 1, 0)

In [299]:
AND(X)

array([[0],
       [0],
       [0],
       [1]])

In [251]:
def NAND(x) :
    W =np.array([[0.1], [0.1]]) 
    theta = 0.11
    return np.where(np.dot(x, W) < theta, 1, 0)

In [252]:
NAND(X)

array([[1],
       [1],
       [1],
       [0]])

In [300]:
def OR(x) :
    W =np.array([[0.2], [0.2]]) 
    theta = 0.03
    return np.where(np.dot(x, W) > theta, 1, 0)

In [301]:
OR(X)

array([[0],
       [1],
       [1],
       [1]])

In [148]:
def XOR(x) :
    x = np.c_[NAND(x), OR(x)]
    return AND(x)

In [149]:
XOR(X)

array([[0],
       [1],
       [1],
       [0]])

In [198]:
def XOR(x) :
    W1 = np.array([[-0.1 ,0.30000000000000004],[-0.1,0.30000000000000004]])
    W2 = np.array([[0.2],[0.2]])    
    b1 = 0.1
    b2 = 0.1
    layer1 = np.where(np.dot(x,W1) > b1, 1, 0)
    layer2 = np.where(np.dot(layer1,W2) > b2, 1, 0)
    return layer2

In [255]:
# AND
w1s = np.linspace(0.1, 1, 10)
w2s = np.linspace(0.1, 1, 10)
thetas = np.linspace(0.1, 1, 10)

for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 > theta, 1, 0)
            if np.sum(result == np.array([0, 0, 0, 1])) == 4:
                break
                print(w1, w2, theta)

In [293]:
# OR
w1s = np.linspace(0.1, 1, 10)
w2s = np.linspace(0.1, 1, 10)
thetas = np.linspace(0.1, 1, 10)

for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 > theta, 1, 0)
            if np.sum(result == np.array([0, 1, 1, 1])) == 4:
                break
                print(w1, w2, theta)

In [295]:
# NAND
w1s = np.linspace(0.1, 1, 10)
w2s = np.linspace(0.1, 1, 50)
thetas = np.linspace(0.1, 1, 10)

for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1 + X[:,1]*w2 < theta, 1, 0)
            if np.sum(result == np.array([1, 1, 1, 0])) == 4:
                break
                print(w1, w2, theta)

In [302]:
def XOR(x):
    # W1 = np.array([[NAND,OR],[NAND,OR]])
    # W2 = np.array([[AND],[AND]])
    # b1 = NAND_theta
    # b2 = OR_theta
    # b3 = AND_theta
    
    W1 = np.array([[0.1,0.1],[0.1,0.7]])
    W2 = np.array([[0.1],[0.1]])
    b1 = 0.11
    b2 = 0.03
    b3 = 0.1
    s1 = np.where(np.dot(x,W1[:,0]) < b1, 1, 0)
    s2 = np.where(np.dot(x,W1[:,1]) > b2, 1, 0)
    s = np.c_[s1, s2]
    result = np.where(np.dot(s,W2) > b3 , 1 ,0)
    return result

In [303]:
XOR(X)

array([[0],
       [1],
       [1],
       [0]])